#ifndef CONSTS_H
#define CONSTS_H

enum ErrCode {
    SYN_ERR_NOT_AN_ID,
    SYN_ERR_CAN_NOT_APPLY,
    RUN_ERR_UNBOUND_VAR,
    SYN_ERR_MISS_OR_EXTRA_EXP,
    SYN_ERR_EMPTY_PARA_LIST,
    RUN_ERR_WRONG_NUM_OF_ARGS,
    SYN_ERR_EMPTY_COMB,
    READ_ERR_UNEXPECTED_RIGHT_BRACKET,
    RUN_ERR_WRONG_TYPE,
    INT_ERR,
    PAR_ERR_ILLEGAL_CHAR_IN_ESC
};

extern const char *ERR_MSG[];

#endif
